name: GitHub metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity"
          plugin_habits: yes
          plugin_habits_from: 300
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          plugin_music: yes
          plugin_music_provider: lastfm  # Use Last.fm as provider
          plugin_music_mode: recent      # Set plugin mode
          plugin_music_limit: 4          # Limit to 4 entries
          plugin_music_user: soul_serpent
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          config_timezone: America/New_York
